name: Deploy Profile Picture

on:
  push:
    paths:
      - 'img/UserProfile/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "21-77830@g.batstate-u.edu.ph"
          git config --global user.name "JamirCute"

      - name: Commit and push changes
        run: |
          git add img/UserProfile
          git commit -m "Auto-commit: Profile picture updated"
          git push origin main

      - name: Add Secret
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.DOCMAP_TOKEN }}
          script: |
            github.rest.repos.createOrUpdateFile({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'img/UserProfile/.gitkeep',
              message: 'Add .gitkeep',
              content: '',
              branch: 'main'
            })
